### ISSUE TITLE
DS012- V6X standard, which are 3 pins  (GPIO) for bootloader?.

### ISSUE THREAD

**Issue by Daywithck** [pixhawk/Pixhawk-Standards#55]
Hi,
     I can see the in block diagram(DS-012 V6X standard) ADIO(8pin JST GH)  3 bits for bootloader.  I couldn't figure out corresponding 3pins used for boot loader in pinout sheet.  but i can guess it like, VBUS_Sense, may be nArmed, ?.   if any one knows, pls share the pin names.  Appreciate your inputs.

**Comment by davids5** [comment]
<img width="692" alt="image" src="https://github.com/user-attachments/assets/c6930738-1ddd-41cb-acd9-bc494adbeb91">


There is some logic on the base. 
FMU_nRST (pin 87 on X1) = !nArmed (Pin 85 on X1)&  FMU_RST_REQ_AUX 
VBUS_SENSE (pin 80 on X1)  = FMU_BOOTLOADER_AUX || VBUS

**Comment by Daywithck** [comment]
make sense. thanks for the update.
